export enum ActivityType {
  WARMUP = 'WARMUP',
  CARDIO = 'CARDIO',
  STRENGTH = 'STRENGTH',
  FLEXIBILITY = 'FLEXIBILITY',
  BALANCE = 'BALANCE',
  COORDINATION = 'COORDINATION',
  CYCLING = 'CYCLING',
  WALKING = 'WALKING',
  RUNNING = 'RUNNING',
  MARTIAL = 'MARTIAL',
}
