export enum MuscleGroup {
  NECK = 'NECK',
  SHOULDERS = 'SHOULDERS',
  CHEST = 'CHEST',
  BACK = 'BACK',
  BICEPS = 'BICEPS',
  TRICEPS = 'TRICEPS',
  FOREARMS = 'FOREARMS',
  ABS = 'ABS',
  GLUTES = 'GLUTES',
  THIGHS = 'THIGHS',
  CALVES = 'CALVES',
}
