spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_terra
    username: fitness_terra
    password: fitness_terra
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        globally_quoted_identifiers: true
#    hibernate:
#      ddl-auto: create
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 5120KB
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    endpoint: storage.yandexcloud.net
    bucket: fitness-terra
    region:
      static: ru-central1
      auto: false
    credentials:
      access-key:
      secret-key:

jwt:
  secret-key:
